### PR TITLE
feat(discovery): add cryostat-agent discovery plugin

### PR DESCRIPTION
**Pull request by andrewazores**
Related to https://github.com/cryostatio/cryostat/issues/936

Just a draft for now, mostly meant to share what the setup looks like to add the new `cryostat-agent` to a Quarkus containerized application.

### CODE REVIEW

**Comment by andrewazores** [comment]
The agent JAR is also now published (automatically) as a package on the GitHub Packages Maven repository:

https://github.com/cryostatio/cryostat-agent/packages/1601815

But this requires a GitHub Personal Access Token to use - GitHub still doesn't allow unauthenticated package downloads. For now I'll stick with using `jitpack` in this draft for the convenience. Ideally we publish the agent JAR to some repository that allows anonymous downloads.

**Review by ebaron — COMMENTED** [review]
Seems good overall. The GitHub Maven repository manual setup seems unfortunate, but I imagine this will integrate more smoothly with CI than needing to clone and `mvn install` the dependency like we do with -core.

**Comment by andrewazores** [comment]
Yea, I tried a few different things (now erased from the commit history) to try to get the CI build working within this PR, but I couldn't figure it out. Always a `401` response when the runner tries to download the agent .jar from the GH repository. But, I think consuming the JAR in this way with the `dependency` plugin is much more palatable than building the agent as a submodule.

**Comment by andrewazores** [comment]
Dropping this, since the Agent is now available on Maven Central as well as on quay.io as an init container (both unauthenticated), and we have other published examples of how to consume the Agent in an application container (ex. test-applications repository).

**Pull request closed without merging**
